apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  selector:
    app: llama-stack
    app.kubernetes.io/instance: ""  # Will be set by field transformation
  ports:
  - name: http
    protocol: TCP
