apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
  - ../../default

patches:
  # patch to remove default `system` namespace in ../../manager/manager.yaml
  - path: delete-namespace.yaml

configMapGenerator:
  - name:  lls-parameters
    behavior: merge
    envs:
      - params.env

configurations:
  - params.yaml

replacements:
  - source:
      kind: ConfigMap
      name: lls-parameters
      version: v1
      fieldPath: data.RELATED_IMAGE_ODH_LLAMASTACK_OPERATOR
    targets:
      - select:
          kind: Deployment
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].image
