name: Build Operator Image

on:
  pull_request_target:
    types: [closed]

permissions:
  actions: write
  contents: read

jobs:
  build-latest-image:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push latest image
        run: make image-build image-push -e IMG=quay.io/llamastack/llama-stack-k8s-operator:latest
