name: Tests Code Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up limgo
        uses: GoTestTools/limgo-action@v1.0.2
        with:
          version: "v1.0.0"
          install-only: true

      - name: Run tests
        run: |
          make test

      - name: Gather and calculate test coverage
        run: |
          limgo -coverfile=cover.out -outfmt=md -outfile=/tmp/covcheck.md -v=4 -config=.limgo.json
          cat /tmp/covcheck.md >> $GITHUB_STEP_SUMMARY

      - name: Upload test coverage results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-coverage-results
          path: /tmp/covcheck.md
          if-no-files-found: error
