name: Build Operator Image

on:
  push:
    branches:
       - main
       - odh

permissions:
  actions: write
  contents: read

jobs:
  build-latest-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push latest image
        run: make docker-build docker-push -e IMG=quay.io/opendatahub/llama-stack-k8s-operator:latest
