name: Build Release Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.1)'
        required: true
        type: string
      release_branch:
        description: 'Release branch name (e.g., release-1.2)'
        required: true
        type: string

permissions:
  actions: write
  contents: read

jobs:
  build-release-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.release_branch }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push release image
        run: |
          make image -e IMG=quay.io/llamastack/llama-stack-k8s-operator:${{ github.event.inputs.version }}
