name: Run E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create kind config
        run: |
          cat > kind-config.yaml << EOF
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          containerdConfigPatches:
          - |-
            [plugins."io.containerd.grpc.v1.cri".registry]
              config_path = "/etc/containerd/certs.d"
          nodes:
          - role: control-plane
            kubeadmConfigPatches:
            - |
              kind: InitConfiguration
              nodeRegistration:
                kubeletExtraArgs:
                  system-reserved: memory=500Mi
                  eviction-hard: memory.available<200Mi
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          EOF

      - name: Create k8s Kind Cluster
        id: kind
        uses: helm/kind-action@v1
        with:
          registry: true
          registry_name: kind-registry
          registry_port: 5000
          registry_enable_delete: true
          config: kind-config.yaml

      - name: Build operator image
        run: |
          # Build the image with a simpler tag format
          docker build -t kind-registry:5000/llama-stack-k8s-operator:pr${{ github.event.pull_request.number }} -f Dockerfile .

          # Tag the image for local registry
          docker tag kind-registry:5000/llama-stack-k8s-operator:pr${{ github.event.pull_request.number }} kind-registry:5000/llama-stack-k8s-operator:latest

      - name: Push operator image to local registry
        run: |
          docker push kind-registry:5000/llama-stack-k8s-operator:latest

      - name: Deploy operator
        run: |
          # Deploy the operator
          make deploy IMG=kind-registry:5000/llama-stack-k8s-operator:latest

          # Wait for operator deployment to be ready
          if ! kubectl wait --for=condition=available --timeout=300s deployment/llama-stack-k8s-operator-controller-manager -n llama-stack-k8s-operator-system; then
            echo "Deployment failed to become ready. Debugging information:"
            kubectl describe deployment llama-stack-k8s-operator-controller-manager -n llama-stack-k8s-operator-system
            kubectl logs -l control-plane=controller-manager -n llama-stack-k8s-operator-system --tail=100
            kubectl get events -n llama-stack-k8s-operator-system --sort-by='.lastTimestamp'
            exit 1
          fi

      - name: Run e2e tests
        run: |
          make test-e2e

      - name: Get logs
        if: ${{ always() }}
        run: |
          kubectl -n llama-stack-test get all -o yaml > all.log
          kubectl -n llama-stack-k8s-operator-system logs deployment.apps/llama-stack-k8s-operator-controller-manager > controller-manager.log
          kubectl -n llama-stack-test describe all > all-describe.log
          kubectl -n llama-stack-test describe events > events.log
          kubectl get llamastackdistributions --all-namespaces -o yaml > llamastackdistributions.log

      - name: Upload all logs to artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: logs-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            *.log
          retention-days: 1
